//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GPGiaitriviet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public long ID { get; set; }
        public string Phone { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string Address { get; set; }
        public string Ward { get; set; }
        public string District { get; set; }
        public string Province { get; set; }
        public Nullable<System.DateTime> Calldate { get; set; }
        public string Note { get; set; }
        public string Editby { get; set; }
        public Nullable<System.DateTime> Editdate { get; set; }
        public Nullable<int> JINTAN { get; set; }
        public Nullable<int> TAOMATTROI { get; set; }
        public string Birthday { get; set; }
        public string Sex { get; set; }
        public string Callby { get; set; }
        public Nullable<int> YearOfBorn { get; set; }
        public Nullable<System.DateTime> LastJinTan { get; set; }
        public Nullable<System.DateTime> LastTaoMatTroi { get; set; }
        public Nullable<int> X30 { get; set; }
        public Nullable<int> NATTO { get; set; }
        public Nullable<System.DateTime> LastX30 { get; set; }
        public Nullable<System.DateTime> LastNatto { get; set; }
        public Nullable<int> OTHER { get; set; }
        public Nullable<System.DateTime> LastOther { get; set; }
    }
}
